### ISSUE TITLE
Errors for Add Event Command could be better specified

### ISSUE THREAD

**Issue by Nicholaskoh1** [AY2425S1-CS2103T-F09-1/tp#140]
As shown below, the error for not possible dates (30 feb) does not correspond to the error shown on screen.
![Screenshot 2024-11-06 165503](https://github.com/user-attachments/assets/a220fa9d-f458-4f92-8c44-f811cbf00050)

**Comment by limyixiang** [comment]
Okay, I will take a look at it, thanks!
