### ISSUE TITLE
[PE-D][Tester D] Events should accept blank fields

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F09-1/tp#202]
![Screenshot 2024-11-08 at 4.42.30 PM.png](https://raw.githubusercontent.com/oolongwater/ped/main/files/fbbac200-6889-4c17-9f90-d1ab463955a4.png)

Perhaps change the event description to accept empty inputs in the case they are optional.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: oolongwater/ped#7

**Comment by limyixiang** [comment]
I guess this makes sense, but it is not a bug. This can't be fixed by v1.6.

**Comment by limyixiang** [comment]
Might add as a possible enhancement.
