### ISSUE TITLE
[PE-D][Tester A] Repetitive instructions 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F09-1/tp#221]
![image.png](https://raw.githubusercontent.com/SSirMentos/ped/main/files/7ff43483-e179-43dd-abf0-1619e414e2e2.png)

unnecessary repetitions as EVENT_INDEX and PERSON INDEX could be combined into one line

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: SSirMentos/ped#5

**Comment by limyixiang** [comment]
Will fix this in the UG
