### ISSUE TITLE
[PE-D][Tester B] AddressBook Level-3 reference in UG and DG

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F09-1/tp#224]
References to AddressBook Level-3 still exist at the top of every page for UG and DG.

![image.png](https://raw.githubusercontent.com/k-hian/ped/main/files/6cf456f6-edb9-4e70-80e7-df4fd590f1ec.png)

![image.png](https://raw.githubusercontent.com/k-hian/ped/main/files/a58b8da1-be47-401d-bd9e-f78c5d6fb3d8.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: k-hian/ped#8

**Comment by limyixiang** [comment]
Will fix this later
